### ISSUE TITLE
Initialization

### ISSUE THREAD

**Issue by clemisch** [nguyenph88/AutoDropBox#1]
I know the last commit was four years ago, but I can't help but cringe over the "Initialization" section. When you don't want people to use this, don't put it up publically and write a long README. 
Either document the installation or don't. But don't be a jerk.

**Comment by nguyenph88** [comment]
hi @clemisch , sorry to disappoint you when you came to the repo and found I I was a so-called 'jerk'. If you take a look at all the commits, I was literally released that for my friend and I didn't write that part until some dudes came up and sent me a lot of requests/cursing how I was ruining their business on Fiverr because of the tool.

To be honest, if you really did read through the whole thing, there were enough clues to craft the vm to handle the jobs at that time. Noone had any problem with that, and yes, only script-kiddie comes and mourns. 

Feel free to reach out to me if needed. My email is on my github's frontpage.

Thanks and have a nice day!
